fedora-sysexts/fedora

- sysext.just
- tools/justfile
sysext.just: Skip steps when they are not needed
---
tools: Add rocm-smi for AMG GPU support in btop
> tools: Add rocm-smi for AMG GPU support in btop

- sysext.just
As we install all packages again in this step, we need the pre commands to make it consistent with the download step.
> sysext.just: Also run pre-commands in SELinux step

- sysext.just
sysext.just: List each extracted packages on its own line
This makes the log more readable in CI.
---
sysext.just: Move /run out of the sysext (ignored)
/run is ignored so let's move it out of the sysext.
> sysext.just: List each extracted packages & Move /run out

- sysext.just
Otherwise this would fail if no package had been set for installation.
> sysext.just: Install packages as needed for SELinux labeling

- .github/workflows/sysexts-fedora-kinoite-41.yml
- .github/workflows/sysexts-fedora-silverblue-41.yml
- firefox/README.md
- firefox/justfile
- update_workflows.sh
While Firefox exists in silverblue/kinoite today, this enables use on downstream images (eg Bazzite and Bluefin) where Firefox is removed from the system image.
> firefox: Add initial sysext

- .github/workflows/containers-fedora-coreos-stable.yml
- .github/workflows/containers-fedora-kinoite-41.yml
- .github/workflows/containers-fedora-silverblue-41.yml
- .github/workflows/sysexts-fedora-coreos-stable.yml
- .github/workflows/sysexts-fedora-kinoite-41.yml
- .github/workflows/sysexts-fedora-silverblue-41.yml
- .workflow-templates/containers_build
- .workflow-templates/containers_header
- .workflow-templates/sysexts_body
- .workflow-templates/sysexts_header
- cri-o-1.29/README.md
- cri-o-1.30/README.md
- cri-o-1.31/README.md
- kubernetes-1.29/README.md
- kubernetes-1.30/README.md
- kubernetes-1.31/README.md
- kubernetes-cri-o-1.29/Containerfile
- kubernetes-cri-o-1.29/README.md
- kubernetes-cri-o-1.29/justfile
- kubernetes-cri-o-1.30/Containerfile
- kubernetes-cri-o-1.30/README.md
- kubernetes-cri-o-1.30/justfile
- kubernetes-cri-o-1.31/Containerfile
- kubernetes-cri-o-1.31/README.md
- kubernetes-cri-o-1.31/justfile
- sysext.just
- update_workflows.sh
sysext.just: Whitespace cleanup
---
sysext.just: Support excluding packages from weak dependencies
Sometimes needed to exclude some packages while still keeping weak
dependencies enabled globally.
See: https://github.com/travier/fedora-sysexts/pull/45
---
workflows: Only build sysexts on PRs with related changes
See: https://github.com/travier/fedora-sysexts/issues/47
---
kubernetes-cri-o-*: Add initial sysexts
Sysext with both Kubernetes and CRI-O. Might replace the standalone
CRI-O sysext in the future.
---
kubernetes-cri-o-*: Exclude unversioned cri-tools dependency
---
cri-o/kubernetes: Add READMEs
> kubernetes-cri-o-*: Add initial sysexts & Add READMEs

- .github/workflows/sysexts-fedora-coreos-stable-aarch64.yml
- .github/workflows/sysexts-fedora-coreos-stable-x86_64.yml
- .github/workflows/sysexts-fedora-kinoite-41-x86_64.yml
- .github/workflows/sysexts-fedora-silverblue-41-x86_64.yml
- .workflow-templates/sysexts_body
- .workflow-templates/sysexts_footer
- .workflow-templates/sysexts_header
- 1password-cli/justfile
- 1password-gui/justfile
- cri-o-1.29/justfile
- cri-o-1.30/justfile
- cri-o-1.31/justfile
- kubernetes-1.29/justfile
- kubernetes-1.30/justfile
- kubernetes-1.31/justfile
- kubernetes-cri-o-1.29/justfile
- kubernetes-cri-o-1.30/justfile
- kubernetes-cri-o-1.31/justfile
- monitoring/justfile
- steam-devices/justfile
- steam/justfile
- sysext.just
- update_workflows.sh
- vscodium/justfile
sysext.just: Rename 'arch' to 'dnf_arch' for dnf download
Split the list of architectures to use with dnf when downloading
packages from the global architecture to build the sysext for.
---
sysext.just: Split build recipe dependency list
---
sysext.just: Support building for non native architectures
Update justfiles to new recipe signature.
---
kubernetes/cri-o: Also build for aarch64
---
workflows: Add support for non x86_64 architectures
---
workflows: Add aarch64 sysexts build for Fedora CoreOS
---
See: https://github.com/travier/fedora-sysexts/issues/49
> Add support for building aarch64 EROFS sysexts

- .github/workflows/containers-fedora-kinoite-41.yml
- .github/workflows/containers-fedora-silverblue-41.yml
- .github/workflows/sysexts-fedora-kinoite-41-x86_64.yml
- .github/workflows/sysexts-fedora-silverblue-41-x86_64.yml
- lact-libadwaita/Containerfile
- lact-libadwaita/README.md
- lact-libadwaita/justfile
- lact/Containerfile
- lact/README.md
- lact/justfile
lact is meant to be used for kde images and lact-libadwaita for gnome.
Tested on Bazzite.
I didn't test gnome.
> feat: add lact

- mpd/Containerfile
adds mpd container build without push and sign
see https://github.com/travier/fedora-sysexts/pull/68
mpdris2 is the component that doesn't work with the host in distrobox/quadlet
related: https://github.com/travier/fedora-sysexts/issues/44
> feat: add mpd container build

- cri-o-1.29/justfile
- cri-o-1.30/justfile
- cri-o-1.31/justfile
- cri-o-1.32/justfile
- docker-ce/README.md
- docker-ce/justfile
- kubernetes-1.29/justfile
- kubernetes-1.30/justfile
- kubernetes-1.31/justfile
- kubernetes-1.32/justfile
- kubernetes-cri-o-1.29/justfile
- kubernetes-cri-o-1.30/justfile
- kubernetes-cri-o-1.31/justfile
- kubernetes-cri-o-1.32/justfile
- libvirtd-desktop/README.md
- libvirtd-desktop/justfile
- libvirtd/README.md
- libvirtd/justfile
- moby-engine/README.md
- moby-engine/justfile
- sysext.just
sysext.just: Support setting up services to uphold
System services that are included in sysexts are not started on boot,
even if enabled.
This works around this issue by using the `Upholds` directive [1] to
make sure that those units are started.
Note that this bypasses the enabled/disabled state, but it is still
possible to mask the unit, or remove the sysext entirely.
This will also set the `EXTENSION_RELOAD_MANAGER=1` option for the
sysexts which tell systemd-sysext to ask systemd to reload its
configuration when the sysexts are loaded [2].
[1]: https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#Upholds=
[2]: https://www.freedesktop.org/software/systemd/man/latest/systemd-sysext.html
See: https://github.com/flatcar/sysext-bakery/blob/87f4af7e579846c6d9c16d7db70f3c …
> sysext.just: Support setting up services to uphold

- kubernetes-1.29/justfile
- kubernetes-1.30/justfile
- kubernetes-1.31/justfile
- kubernetes-1.32/justfile
- kubernetes-cri-o-1.29/justfile
- kubernetes-cri-o-1.30/justfile
- kubernetes-cri-o-1.31/justfile
- kubernetes-cri-o-1.32/justfile
kubernetes*: Remove kubernetes-systemd subpackage
This is not needed when setting up the cluster with kubeadm, i.e. hosted
control plane.
---
kubernetes*: Setup kubelet-plugins/volume/exec folder
kubelet expects this folder to exists and looks at it to find
additional third party volume plugins.
Those plugins could be added to this folder via another sysext for
example.
See: https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
See: https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/
> kubernetes*: Collection of small fixes

- .github/workflows/sysexts-fedora-kinoite-41-x86_64.yml
- .github/workflows/sysexts-fedora-kinoite-42-x86_64.yml
- .github/workflows/sysexts-fedora-silverblue-41-x86_64.yml
- .github/workflows/sysexts-fedora-silverblue-42-x86_64.yml
- 1password-gui/Containerfile
- bitwarden/Containerfile
- bitwarden/Justfile
- bitwarden/README.md
- mullvad-vpn/Containerfile
This PR adds the official [Bitwarden](https://bitwarden.com/) app. The installation is remarkably similar to 1Password.
While Bitwarden maintains an official flatpak package on Flathub, some features are only available with the packaged application.
> feat: Add Bitwarden sysext

- .github/workflows/sysexts-fedora-silverblue-41-x86_64.yml
- .github/workflows/sysexts-fedora-silverblue-42-x86_64.yml
- openssl/Containerfile
- openssl/README.md
- openssl/justfile
Needed for the GSconnect shell extension on Silverblue.
See: https://github.com/fedora-silverblue/issue-tracker/issues/201
> openssl: Initial sysext

- update_workflows.sh
Currently, the generated shortname has only the first space replaced with a hyphen:
"Fedora Sway Atomic" becomes "fedora-sway atomic"
with this change:
"Fedora Sway Atomic" becomes "fedora-sway-atomic"
This'll save the annoyance of spaces in filenames particularly if/when you enable builds for the other atomic variants.
> fix: replace all spaces in shortname

- .github/workflows/sysexts-fedora-coreos-next-aarch64.yml
- .github/workflows/sysexts-fedora-coreos-next-x86_64.yml
- .github/workflows/sysexts-fedora-coreos-stable-aarch64.yml
- .github/workflows/sysexts-fedora-coreos-stable-x86_64.yml
- cilium-cli/justfile
- sysext.just
- youki/justfile
sysext.just: Lock sysexts to matching ID/VERSION_ID
The sysexts built in this repos are built for Fedora and for specific
releases. Set the ID and VERSION_ID in the extension config file in
order to tell systemd-sysext to only use those sysexts on systems with
matching ID/VERSION_ID.
---
cilium-cli: Add initial sysext
---
youki: Add initial sysext
> Add cilium-cli, youki & lock sysexts to matching ID/VERSION_ID

- .github/actions/build/action.yml
- gdb/justfile
- incus/justfile
- inxi/justfile
- iwd/justfile
- kubernetes-1.29/justfile
- kubernetes-1.30/justfile
- kubernetes-1.31/justfile
- kubernetes-1.32/justfile
- kubernetes-1.33/justfile
- kubernetes-cri-o-1.29/justfile
- kubernetes-cri-o-1.30/justfile
- kubernetes-cri-o-1.31/justfile
- kubernetes-cri-o-1.32/justfile
- kubernetes-cri-o-1.33/justfile
- nordvpn-gui/justfile
- nordvpn/justfile
- semanage/justfile
- steam-kinoite/justfile
- steam-silverblue/justfile
- sysext.just
- tailscale/justfile
sysext.just: Fix arch names to match what systemd expects
See: https://www.freedesktop.org/software/systemd/man/latest/sysupdate.d.html#Specifiers
See: https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#ConditionArchitecture=
Fixes: https://github.com/travier/fedora-sysexts/issues/125
---
sysext.just: Centralize podman options
---
sysext.just: Ignore empty directories in /var /run /opt
There isn't much value in erroring out on empty directories in /var,
/run or /opt as it is common for RPMs to include those files, even if
they use tmpfiles.d configs. Let's clear them by default to simplify
justfiles and reduce the amount of errors in CI on updates.
---
*: Remove all manual /var, /opt & /run cleanupSee: https://www.freedesktop.org/software/systemd/man/latest/sysupdate …
> sysext.just: Fix arch names to match what systemd expects

- gdb/justfile
- inxi/justfile
- kubernetes-1.29/justfile
- kubernetes-1.30/justfile
- kubernetes-1.31/justfile
- kubernetes-1.32/justfile
- kubernetes-1.33/justfile
- kubernetes-cri-o-1.29/justfile
- kubernetes-cri-o-1.30/justfile
- kubernetes-cri-o-1.31/justfile
- kubernetes-cri-o-1.32/justfile
- kubernetes-cri-o-1.33/justfile
- sysext.just
kubernetes-cri-o-1.33: cri-o1.33 now in stable repos
---
sysext.just: Add option to cleanup selected files
This will simplify the cleanup logic for most sysexts where only a few
files need to be removed from /var for example.
---
*: Use cleanup_files option
>  sysext.just: Add option to cleanup selected files and use it

- libvirtd-desktop/justfile
This should be pulled as a dependency but for some reason it's not. Let's manually include it for now.
See: https://github.com/travier/fedora-sysexts/issues/116
Fixes: https://github.com/travier/fedora-sysexts/issues/129
> libvirtd-desktop: Explicitly include osinfo-db & osinfo-db-tools

- tailscale/justfile
- tailscale/usr/lib/systemd/system/tailscaled.service.d/50-sysext-default.conf
To clear entry, the value must be absent. Current file are warned like so, and systemd doesn't start unit due to `resources` error when I don't have the original file:
```text
systemd[1]: /usr/lib/systemd/system/tailscaled.service.d/50-sysext-default.conf:3: EnvironmentFile= path is not absolute, ignoring: ""
systemd[1]: tailscaled.service: Failed to load environment files: No such file or directory
systemd[1]: tailscaled.service: Failed to spawn 'start' task: No such file or directory
```
> tailscale: fix override file

- .github/workflows/sysexts-fedora.yml
- openconnect/README.md
- openconnect/justfile
The primary motivation for creating this extension is to address a critical bug in `openconnect-9.12-7` (the version currently available in Fedora 42) that prevents successful connections to certain VPN configurations. This bug is tracked here:
[https://gitlab.com/openconnect/openconnect/-/issues/659](https://gitlab.com/openconnect/openconnect/-/issues/659)
> openconnect: Add initial sysext

- tailscale/justfile
- tailscale/usr/lib/systemd/system/tailscaled.service.d/50-sysext-default.conf
Looks like the package is not including or using this file in the
systemd unit anymore.
Fixes: #146
> tailscale: Remove 'default' EnvironmentFile workaround

- sysext.just
Set `JUST_PODMAN_EXTRA_OPTS` to pass extra opts to podman commands. Use `--pull=never` for example to disable image update checks and pulls
> sysext.just: Support passing extra args to podman commands

- .github/docs-templates/body.md
In order for newly installed sysext to show up, sysexts need to be refreshed. It would be useful to add this information to the docs
> docs: merge Installation and Merging sections

- sysext.just
Disable to the repo by default to make sure that we never install it in a sysext by mistake.
> sysext.just: Disable openh264 repo by default

- .github/actions/build/action.yml
This reverts commit aae4208.Revert "github/actions/build: Retry on 'release create' failure"
This reverts commit aae420857491252f9bd204a1a1c05abe83e987b4.
---
github/actions/build: Ignore 'gh release create' failures
Ignore failures as those are generally GitHub API flakes and the release
does get created. If it does not, it will be on the next run the next
day.
> github/actions/build: Ignore 'gh release create' failures

- docs/index.md
- libvirtd/justfile
docs: Move compatibility note to the shared docs
---
libvirtd: nfs-utils-coreos fixed in F44
> docs: Move compatibility note to the shared docs
